stages:
  - "build_image"

build_image:
  stage: build_image
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  tags:
    - hva
  only:
    refs:
      - staging

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
